# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryGameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGame = channel.unary_unary(
                '/memory.v1.MemoryGameService/JoinGame',
                request_serializer=memory__pb2.JoinGameRequest.SerializeToString,
                response_deserializer=memory__pb2.JoinGameResponse.FromString,
                _registered_method=True)
        self.PlayMove = channel.unary_unary(
                '/memory.v1.MemoryGameService/PlayMove',
                request_serializer=memory__pb2.PlayMoveRequest.SerializeToString,
                response_deserializer=memory__pb2.PlayMoveResponse.FromString,
                _registered_method=True)
        self.GetBoardState = channel.unary_unary(
                '/memory.v1.MemoryGameService/GetBoardState',
                request_serializer=memory__pb2.GetBoardStateRequest.SerializeToString,
                response_deserializer=memory__pb2.BoardState.FromString,
                _registered_method=True)
        self.SubscribeToUpdates = channel.unary_stream(
                '/memory.v1.MemoryGameService/SubscribeToUpdates',
                request_serializer=memory__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=memory__pb2.GameUpdate.FromString,
                _registered_method=True)
        self.KickPlayer = channel.unary_unary(
                '/memory.v1.MemoryGameService/KickPlayer',
                request_serializer=memory__pb2.KickPlayerRequest.SerializeToString,
                response_deserializer=memory__pb2.KickPlayerResponse.FromString,
                _registered_method=True)
        self.ResetGame = channel.unary_unary(
                '/memory.v1.MemoryGameService/ResetGame',
                request_serializer=memory__pb2.ResetGameRequest.SerializeToString,
                response_deserializer=memory__pb2.ResetGameResponse.FromString,
                _registered_method=True)
        self.ListGames = channel.unary_unary(
                '/memory.v1.MemoryGameService/ListGames',
                request_serializer=memory__pb2.ListGamesRequest.SerializeToString,
                response_deserializer=memory__pb2.ListGamesResponse.FromString,
                _registered_method=True)
        self.GetGameStats = channel.unary_unary(
                '/memory.v1.MemoryGameService/GetGameStats',
                request_serializer=memory__pb2.GetGameStatsRequest.SerializeToString,
                response_deserializer=memory__pb2.GetGameStatsResponse.FromString,
                _registered_method=True)


class MemoryGameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoardState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KickPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryGameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=memory__pb2.JoinGameRequest.FromString,
                    response_serializer=memory__pb2.JoinGameResponse.SerializeToString,
            ),
            'PlayMove': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayMove,
                    request_deserializer=memory__pb2.PlayMoveRequest.FromString,
                    response_serializer=memory__pb2.PlayMoveResponse.SerializeToString,
            ),
            'GetBoardState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoardState,
                    request_deserializer=memory__pb2.GetBoardStateRequest.FromString,
                    response_serializer=memory__pb2.BoardState.SerializeToString,
            ),
            'SubscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUpdates,
                    request_deserializer=memory__pb2.SubscribeRequest.FromString,
                    response_serializer=memory__pb2.GameUpdate.SerializeToString,
            ),
            'KickPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.KickPlayer,
                    request_deserializer=memory__pb2.KickPlayerRequest.FromString,
                    response_serializer=memory__pb2.KickPlayerResponse.SerializeToString,
            ),
            'ResetGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetGame,
                    request_deserializer=memory__pb2.ResetGameRequest.FromString,
                    response_serializer=memory__pb2.ResetGameResponse.SerializeToString,
            ),
            'ListGames': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGames,
                    request_deserializer=memory__pb2.ListGamesRequest.FromString,
                    response_serializer=memory__pb2.ListGamesResponse.SerializeToString,
            ),
            'GetGameStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameStats,
                    request_deserializer=memory__pb2.GetGameStatsRequest.FromString,
                    response_serializer=memory__pb2.GetGameStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.MemoryGameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.MemoryGameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryGameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryGameService/JoinGame',
            memory__pb2.JoinGameRequest.SerializeToString,
            memory__pb2.JoinGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryGameService/PlayMove',
            memory__pb2.PlayMoveRequest.SerializeToString,
            memory__pb2.PlayMoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoardState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryGameService/GetBoardState',
            memory__pb2.GetBoardStateRequest.SerializeToString,
            memory__pb2.BoardState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memory.v1.MemoryGameService/SubscribeToUpdates',
            memory__pb2.SubscribeRequest.SerializeToString,
            memory__pb2.GameUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KickPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryGameService/KickPlayer',
            memory__pb2.KickPlayerRequest.SerializeToString,
            memory__pb2.KickPlayerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryGameService/ResetGame',
            memory__pb2.ResetGameRequest.SerializeToString,
            memory__pb2.ResetGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryGameService/ListGames',
            memory__pb2.ListGamesRequest.SerializeToString,
            memory__pb2.ListGamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryGameService/GetGameStats',
            memory__pb2.GetGameStatsRequest.SerializeToString,
            memory__pb2.GetGameStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
